// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCipO1EjJUoPmg3yL-ejaMuIDQyH80i_Tc',
    appId: '1:340732282883:web:dc624cfe0d99c6f0102636',
    messagingSenderId: '340732282883',
    projectId: 'vozanimal-e61f8',
    authDomain: 'vozanimal-e61f8.firebaseapp.com',
    storageBucket: 'vozanimal-e61f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFIpWsM6rFOL1zx-C8PnpAPXQ47jxsLLQ',
    appId: '1:340732282883:android:578ee85a62a6a815102636',
    messagingSenderId: '340732282883',
    projectId: 'vozanimal-e61f8',
    storageBucket: 'vozanimal-e61f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAN85PwvwsWJ59GmgdZwoXhDRTvl0ii9A',
    appId: '1:340732282883:ios:67a9c62f7626830f102636',
    messagingSenderId: '340732282883',
    projectId: 'vozanimal-e61f8',
    storageBucket: 'vozanimal-e61f8.firebasestorage.app',
    iosBundleId: 'com.vozanimal.vozAnimal',
  );

}